### ISSUE TITLE
Rendering error with very long animated element

### ISSUE THREAD

**Issue by SteffenDE** [WebPlatformForEmbedded/WPEWebKit#434]
### Summary
I've noticed a weird error when having a scrolling newsticker that renders a very long list which is mostly out of view.
After a while the content just stops. But as soon as something on the page changes, the content appears again.
The element that is animated is (according to the Chrome devtools) about 60000px wide.

### Hardware and Build
I'm using a Raspberry Pi 3 with the latest buildroot build, but it's the same with all versions I tested (from buildroot and meta-wpe).

### Steps to Reproduce:
A video is available [here](https://s3.eu-central-1.amazonaws.com/steffend/public/wpe-test-rpi3/rss-scroller/vid.mp4) and the displayed page for reproduction [here](https://s3.eu-central-1.amazonaws.com/steffend/public/wpe-test-rpi3/rss-scroller/rss.html).

### Expected Results
The ticker should scroll until all content was visible (open the example in Safari/Chrome/Firefox).

### Actual Results
The content disappears until something on the page changes.

**Comment by SteffenDE** [comment]
I'm seeing a similar problem here: https://s3.eu-central-1.amazonaws.com/steffend/public/webkitbug/scrolling.html

This doesn't only affect WPE, but also all other WebKit based Browsers I tested (Safari, Safari Tech Preview, WebKit Nightly, Mobile Safari), although not in the same way as seen with WPE:
[WPE master using buildroot](https://s3.eu-central-1.amazonaws.com/steffend/public/webkitbug/WPEScrollBug.mp4)
[Comparison: Chrome 63 / Safari 11.0.2 / Safari Tech Preview 47](https://s3.eu-central-1.amazonaws.com/steffend/public/webkitbug/WebKitBug.mp4)
[WebKit Nightly build r227005](https://s3.eu-central-1.amazonaws.com/steffend/public/webkitbug/227005.mp4)
[Mobile Safari iOS 11.2.2](https://s3.eu-central-1.amazonaws.com/steffend/public/webkitbug/MobileSafari.mp4)

Do you think I should open an issue in the main WebKit repo? I noticed the same "content-disappearing-thing" on MobileSafari too (same page), but couldn't reproduce it reliably.

As this is a basic CSS animation I think this issue is **critical**. I'm using this technique in production and therefore I am currently depending on Chromium, which is working as expected.

The animation:
```css
@keyframes scrolllistTicker {
    0% {
        transform: translate3d(0, 0%, 0);
    }
    100% {
        transform: translate3d(0, -50%, 0);
    }
}

.longlist .tickerScroll {
    animation-iteration-count: infinite;
    animation-timing-function: linear;
    animation-name: scrolllistTicker;
}
```
